defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 

development:
  database: questions_development
  <<: *defaults

test:
  database: questions_test
  <<: *defaults
  
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

